// <auto-generated />
namespace VehicleApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BaseEntityDateUpdatedSetToNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BaseEntityDateUpdatedSetToNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202006041157466_BaseEntityDateUpdatedSetToNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
